[phases.build]
  cmd = "npm cache clean --force && npm install --omit=dev --no-audit --no-fund && npm run build"

[phases.start]
  cmd = "node dist/index.js"

[variables]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"