[phases.build]
  cmd = "npm cache clean --force && npm install --omit=dev --no-audit --no-fund && vite build && npx esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/production.js"

[phases.start]
  cmd = "node dist/production.js"

[variables]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"