[phases.build]
  cmd = "echo 'NODE VERSION:' && node --version && echo 'NPM VERSION:' && npm --version && echo 'CLEANING CACHE...' && npm cache clean --force && echo 'INSTALLING DEPS...' && npm install --omit=dev --no-audit --no-fund --verbose && echo 'VITE BUILD...' && npx vite build --mode=production && echo 'ESBUILD SIMPLE...' && npx esbuild server/simple-production.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/simple-production.js --log-level=verbose && echo 'BUILD COMPLETE - FILES:' && ls -la dist/ && echo 'SIMPLE-PRODUCTION.JS HEAD:' && head -5 dist/simple-production.js"

[phases.start]
  cmd = "echo 'STARTING SIMPLE SERVER...' && ls -la dist/ && echo 'NODE ENV:' $NODE_ENV && echo 'PORT:' $PORT && echo 'HOST:' $HOST && node dist/simple-production.js"

[variables]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  SESSION_SECRET = "railway-production-secret-2025"
  HOST = "0.0.0.0"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"