[phases.build]
  cmd = "echo 'NODE VERSION:' && node --version && echo 'NPM VERSION:' && npm --version && echo 'CLEANING CACHE...' && npm cache clean --force && echo 'INSTALLING DEPS...' && npm install --omit=dev --no-audit --no-fund && echo 'ESBUILD DEBUG...' && npx esbuild server/railway-debug.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/railway-debug.js && echo 'BUILD COMPLETE - FILES:' && ls -la dist/ && echo 'TESTING LOCALLY:' && cd dist && PORT=12345 timeout 2s node railway-debug.js || echo 'LOCAL TEST DONE'"

[phases.start]
  cmd = "echo 'STARTING DEBUG SERVER...' && ls -la dist/ && echo 'NODE ENV:' $NODE_ENV && echo 'PORT:' $PORT && echo 'HOST:' $HOST && node dist/railway-debug.js"

[variables]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  SESSION_SECRET = "railway-production-secret-2025"
  HOST = "0.0.0.0"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"