services:
  - type: web
    name: cash-crash-app
    env: node
    runtime: node
    plan: free
    buildCommand: npm ci --omit=dev && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1