services:
  - type: web
    name: cash-or-crash
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/render-full.cjs
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true